#ifndef UE4SS_SDK_ABP_MonsterBase_HPP
#define UE4SS_SDK_ABP_MonsterBase_HPP

struct FAnimBlueprintGeneratedConstantData : public FAnimBlueprintConstantData
{
    FName __NameProperty_385;
    FName __NameProperty_386;
    FName __NameProperty_387;
    FName __NameProperty_388;
    FName __NameProperty_389;
    FName __NameProperty_390;
    FName __NameProperty_391;
    FName __NameProperty_392;
    int32 __IntProperty_393;
    FName __NameProperty_394;
    int32 __IntProperty_395;
    FName __NameProperty_396;
    int32 __IntProperty_397;
    FName __NameProperty_398;
    int32 __IntProperty_399;
    FInputScaleBiasClampConstants __StructProperty_400;
    float __FloatProperty_401;
    FName __NameProperty_402;
    int32 __IntProperty_403;
    bool __BoolProperty_404;
    float __FloatProperty_405;
    EAnimSyncMethod __EnumProperty_406;
    TEnumAsByte<EAnimGroupRole> __ByteProperty_407;
    FName __NameProperty_408;
    FName __NameProperty_409;
    int32 __IntProperty_410;
    class UBlendProfile* __BlendProfile_411;
    class UCurveFloat* __CurveFloat_412;
    bool __BoolProperty_413;
    EAlphaBlendOption __EnumProperty_414;
    EBlendListTransitionType __EnumProperty_415;
    TArray<float> __ArrayProperty_416;
    FAnimNodeFunctionRef __StructProperty_417;
    FAnimSubsystem_PropertyAccess AnimBlueprintExtension_PropertyAccess;
    FAnimSubsystem_Base AnimBlueprintExtension_Base;

};

struct FAnimBlueprintGeneratedMutableData : public FAnimBlueprintMutableData
{
    float __FloatProperty;
    float __FloatProperty_0;
    float __FloatProperty_1;
    float __FloatProperty_2;
    bool __BoolProperty_3;
    bool __BoolProperty_4;
    bool __BoolProperty_5;
    float __FloatProperty_6;
    float __FloatProperty_7;
    float __FloatProperty_8;
    bool __BoolProperty_9;
    bool __BoolProperty_10;
    float __FloatProperty_11;
    float __FloatProperty_12;
    float __FloatProperty_13;
    float __FloatProperty_14;
    bool __BoolProperty_15;
    float __FloatProperty_16;
    float __FloatProperty_17;
    float __FloatProperty_18;
    float __FloatProperty_19;
    TArray<float> __ArrayProperty_20;
    bool __BoolProperty_21;
    bool __BoolProperty_22;
    bool __BoolProperty_23;

};

class UABP_MonsterBase_C : public UPalAnimInstance
{
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;
    FAnimSubsystemInstance AnimBlueprintExtension_PropertyAccess;
    FAnimSubsystemInstance AnimBlueprintExtension_Base;
    FAnimNode_Root AnimGraphNode_Root_5;
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_5;
    FAnimNode_Root AnimGraphNode_Root_4;
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_4;
    FAnimNode_Root AnimGraphNode_Root_3;
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_3;
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_2;
    FAnimNode_Root AnimGraphNode_Root_2;
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose_1;
    FAnimNode_Root AnimGraphNode_Root_1;
    FAnimNode_LinkedInputPose AnimGraphNode_LinkedInputPose;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_13;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_12;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_8;
    FAnimNode_StateResult AnimGraphNode_StateResult_5;
    FAnimNode_LinkedAnimLayer AnimGraphNode_LinkedAnimLayer_4;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_7;
    FAnimNode_StateResult AnimGraphNode_StateResult_4;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_6;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_8;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;
    FAnimNode_StateResult AnimGraphNode_StateResult_3;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_5;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_7;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;
    FAnimNode_StateResult AnimGraphNode_StateResult_2;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;
    FAnimNode_StateResult AnimGraphNode_StateResult_1;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_6;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_4;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_5;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_4;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_3;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_2;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_3;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_1;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer;
    FAnimNode_StateResult AnimGraphNode_StateResult;
    FAnimNode_StateMachine AnimGraphNode_StateMachine;
    FAnimNode_Slot AnimGraphNode_Slot_1;
    FAnimNode_Slot AnimGraphNode_Slot;
    FAnimNode_LinkedAnimLayer AnimGraphNode_LinkedAnimLayer_3;
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_4;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_9;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_2;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_8;
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_3;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_7;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_1;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_6;
    FAnimNode_LinkedAnimLayer AnimGraphNode_LinkedAnimLayer_2;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_5;
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_4;
    FAnimNode_LinkedAnimLayer AnimGraphNode_LinkedAnimLayer_1;
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_2;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_3;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_2;
    FAnimNode_LinkedAnimLayer AnimGraphNode_LinkedAnimLayer;
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_1;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_1;
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose;
    class UPalCharacterMovementComponent* K2Node_PropertyAccess_17;
    bool K2Node_PropertyAccess_15;
    class UPalCharacterMovementComponent* K2Node_PropertyAccess_14;
    bool K2Node_PropertyAccess_12;
    float K2Node_PropertyAccess_10;
    float K2Node_PropertyAccess_9;
    FVector K2Node_PropertyAccess_8;
    bool K2Node_PropertyAccess_7;
    FWeaponAnimationInfo K2Node_PropertyAccess_6;
    FVector K2Node_PropertyAccess_5;
    FVector K2Node_PropertyAccess_3;
    FRotator K2Node_PropertyAccess_2;
    bool K2Node_PropertyAccess_1;
    bool K2Node_PropertyAccess;
    FRotator __CustomProperty_AimRotator_D409488B47D1A68373AC2E9D883DDF47;
    FPalCustomAnimOverrideData __CustomProperty_CustomData_9AE2D5D340DF8B3B12C1E3BFF35496F6;
    FVector __CustomProperty_LookAtWorldLocation_FBA1F7A649A7D6231954198C8C515A62;
    bool IsAiming;
    bool IsShooting;
    FWeaponAnimationInfo WeaponAnimInfo;
    FVector2D CameraVelocityXY;
    FRotator AimRotator;
    bool IsLookatEnable;
    FVector LookAtTarget;
    double LookatInTime;
    double LookatOutTime;
    bool IsJumpPreliminary;
    bool IsSkipJumpStart;
    double AngleSpeed;
    bool IsRiding;
    bool IsFlying;
    bool ShouldBeUseShooterComponent;
    bool ShouldBeUseRiderComponent;
    double PrevMoveSpeed;
    class UNiagaraSystem* FootStepEffectClass;
    FName FootStepAttachPointName;
    class UNiagaraComponent* FootStepEffect;
    class APalCharacter* TSCached_OwnerPalCharacter;
    class UPalShooterComponent* TSCached_ShooterComponent;
    class UPalLookAtComponent* TSCached_LookAtComponent;
    class UPalRideMarkerComponent* TSCached_RideMarker;
    bool IsSpawnDashEffect;
    double DashEffectSpeed;
    bool IsFloating;
    double MovementScale;
    bool IsEnableCustom;
    FPalCustomAnimOverrideData CustomAnmData;

    void MonsterPhysics(FPoseLink InPose, FPoseLink& MonsterPhysics);
    void CustomOverride(FPoseLink PrePose, FPalCustomAnimOverrideData CustomData, FPoseLink& CustomOverride);
    void UpperOverride(FPoseLink NativePose, FPoseLink ActionPose, FPoseLink& UpperOverride);
    void LookAtOverride(FPoseLink InPose, FVector LookAtWorldLocation, FPoseLink& LookAtOverride);
    void AimingOverride(FPoseLink DefaultPose, FRotator AimRotator, FPoseLink& AimingOverride);
    void AnimGraph(FPoseLink& AnimGraph);
    void IsFloatingPal();
    void MakeSwitchStatePalSize(class APalMonsterCharacter* Pal, FString& PalSize);
    void PlayLandingSound();
    void UpdateDashEffect_AnyThread();
    void BlueprintThreadSafeUpdateAnimation(float DeltaTime);
    void GetFootStepEffectScale(double& Scale);
    void GetFootStepCharacterSpeed(double& CharacterSpeed);
    void CanSpawnFootStepEffect(bool& CanSpawn);
    void StopFootStepEffect();
    void StartFootStepEffect();
    void PostUpdateDashEffect();
    void PlaySound(FName SoundId);
    void GetSprint(bool& IsSprint);
    void UpdateRidingParameter();
    void UpdateBasicParameter();
    void Update Look at Parameter();
    void UpdateShooterParameter();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_6FEC962E4C28F1AC8D56A49C89C4ADFA();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_C95153CD4007A62F8D752891550DF5D9();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_925DF20E402882570857548CCD9E3C68();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_ECFECB414886E0974195E991463ACD99();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_40ADA346423143A5CAA0D4B50B157F15();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_ADBAEE7E4B8D4BFED7B43DBC07178B76();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_128A52BB436E9B3A31FBB7A0A5CC15C1();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_672678E246E619FB275DE5AFE6DDA234();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_B62C4ED042628BD16274AFA4FDD16719();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_FE682B1C41C3E7BF960F52B352036D22();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_E84338B149C6CA71A04CD2A2AFEE1A26();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_FB442B974C195CB35B6129B622134627();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_EA0B5CD54E5A85E50831B98555463D29();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_4E7234914642EC3906BB34ADB2B67E5B();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_EE0E56854535C9DCA7F729A194F159F1();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_CE52F1054119833750D5A6BE24F3D0CF();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F0D464AD4B31CE2D2A7A7EA95C239B70();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_845861904B222DFF48071BB93A897E85();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_6D5D23194B5DCCF74E79899BDAC0B9BA();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_A47488D6499D3064732F10A46F49E205();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_8E5298E14CFFC43AC4CB97899CB66188();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F48506EF4272DE0D9403FC8091658CC2();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_56B64F4E4C9E82DE226407ACE61B8F62();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_94EBA2794624A1AE0E87B0B8F0C035CA();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_12D0A21548EC4F9A1B3A7F89B42E002E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F96787034784DF12FF90028A34BB8B39();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_CC343FAC4253DD28BB7769A172EA64C3();
    void BlueprintUpdateAnimation(float DeltaTimeX);
    void BlueprintBeginPlay();
    void BlueprintPostEvaluateAnimation();
    void AnimNotify_Landing();
    void ExecuteUbergraph_ABP_MonsterBase(int32 EntryPoint);
};

#endif
